spring.application.name=fitpro

spring.datasource.url=jdbc:postgresql://localhost:5432/fitpro_db
spring.datasource.username=postgres
spring.datasource.password=Dp1234

spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=fitpro_super_secret_key_make_it_long_2024_abcdefgh
jwt.expiration=86400000

# ADD THESE NEW LINES
spring.mvc.pathmatch.use-suffix-pattern=false
server.error.include-message=always
server.error.include-binding-errors=always